#!/usr/bin/env bash
set -euo pipefail

# Tavok Setup Script
# Generates .env with secure random secrets for production deployment.

echo ""
echo "======================================="
echo "         Tavok Setup Script"
echo "======================================="
echo ""

# Check for existing .env
if [ -f .env ]; then
  echo ".env file already exists."
  read -rp "Overwrite? (y/N): " confirm
  if [[ ! "$confirm" =~ ^[yY]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# Generate secrets
# openssl base64 can wrap lines; strip newlines for .env safety.
NEXTAUTH_SECRET=$(openssl rand -base64 32 | tr -d '\n')
JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n')
INTERNAL_API_SECRET=$(openssl rand -base64 32 | tr -d '\n')
SECRET_KEY_BASE=$(openssl rand -base64 64 | tr -d '\n')
ENCRYPTION_KEY=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -d '=+/')

# Ask for domain
echo ""
read -rp "Your domain (e.g., chat.example.com) or press Enter for localhost: " DOMAIN
DOMAIN=${DOMAIN:-localhost}

if [ "$DOMAIN" = "localhost" ]; then
  NEXTAUTH_URL="http://localhost:3000"
  GATEWAY_WS_URL="ws://localhost:4001/socket"
  CADDY_ENABLED="false"
else
  NEXTAUTH_URL="https://${DOMAIN}"
  GATEWAY_WS_URL="wss://${DOMAIN}/socket"
  CADDY_ENABLED="true"
fi

# Write .env
GENERATED_AT=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
echo "# Tavok Configuration" > .env
echo "# Generated by setup.sh on ${GENERATED_AT}" >> .env
echo "# Keep this file secret. Never commit it to git." >> .env
echo "" >> .env
echo "# ============================================================" >> .env
echo "# DOMAIN & URLs" >> .env
echo "# ============================================================" >> .env
echo "" >> .env
echo "DOMAIN=${DOMAIN}" >> .env
echo "NEXTAUTH_URL=${NEXTAUTH_URL}" >> .env
echo "NEXT_PUBLIC_GATEWAY_URL=${GATEWAY_WS_URL}" >> .env
echo "" >> .env
echo "# ============================================================" >> .env
echo "# DATABASE" >> .env
echo "# ============================================================" >> .env
echo "" >> .env
echo "POSTGRES_USER=tavok" >> .env
echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
echo "POSTGRES_DB=tavok" >> .env
echo "DATABASE_URL=postgresql://tavok:${POSTGRES_PASSWORD}@db:5432/tavok" >> .env
echo "" >> .env
echo "# ============================================================" >> .env
echo "# SECRETS (auto-generated, do not share)" >> .env
echo "# ============================================================" >> .env
echo "" >> .env
echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}" >> .env
echo "JWT_SECRET=${JWT_SECRET}" >> .env
echo "INTERNAL_API_SECRET=${INTERNAL_API_SECRET}" >> .env
echo "SECRET_KEY_BASE=${SECRET_KEY_BASE}" >> .env
echo "ENCRYPTION_KEY=${ENCRYPTION_KEY}" >> .env
echo "" >> .env
echo "# ============================================================" >> .env
echo "# SERVICE PORTS" >> .env
echo "# ============================================================" >> .env
echo "" >> .env
echo "GATEWAY_PORT=4001" >> .env
echo "STREAMING_PORT=4002" >> .env
echo "" >> .env
echo "# ============================================================" >> .env
echo "# ENVIRONMENT" >> .env
echo "# ============================================================" >> .env
echo "" >> .env
echo "NODE_ENV=production" >> .env
echo "MIX_ENV=prod" >> .env

echo ""
echo ".env file created with secure secrets."
echo ""
if [ "$DOMAIN" != "localhost" ]; then
  echo "Next steps:"
  echo "  1. Point DNS for ${DOMAIN} to this server's IP"
  echo "  2. Run: docker compose --profile production up -d"
  echo "  3. Open https://${DOMAIN}"
  echo ""
  echo "Caddy will automatically obtain an HTTPS certificate."
else
  echo "Next steps:"
  echo "  1. Run: docker compose up -d"
  echo "  2. Open http://localhost:3000"
fi
echo ""
