package bootstrap

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type Secrets struct {
	NextAuthSecret    string
	JWTSecret         string
	InternalAPISecret string
	SecretKeyBase     string
	EncryptionKey     string
	PostgresPassword  string
}

type Config struct {
	Domain            string
	GeneratedAt       time.Time
	NextAuthURL       string
	GatewayURL        string
	PostgresPassword  string
	NextAuthSecret    string
	JWTSecret         string
	InternalAPISecret string
	SecretKeyBase     string
	EncryptionKey     string
}

func BuildConfig(domain string, generatedAt time.Time, secrets Secrets) Config {
	normalizedDomain := normalizeDomain(domain)
	nextAuthURL := "http://localhost:5555"
	gatewayURL := "ws://localhost:4001/socket"

	if normalizedDomain != "localhost" {
		nextAuthURL = fmt.Sprintf("https://%s", normalizedDomain)
		gatewayURL = fmt.Sprintf("wss://%s/socket", normalizedDomain)
	}

	return Config{
		Domain:            normalizedDomain,
		GeneratedAt:       generatedAt.UTC(),
		NextAuthURL:       nextAuthURL,
		GatewayURL:        gatewayURL,
		PostgresPassword:  secrets.PostgresPassword,
		NextAuthSecret:    secrets.NextAuthSecret,
		JWTSecret:         secrets.JWTSecret,
		InternalAPISecret: secrets.InternalAPISecret,
		SecretKeyBase:     secrets.SecretKeyBase,
		EncryptionKey:     secrets.EncryptionKey,
	}
}

func RenderEnv(config Config) string {
	generatedAt := config.GeneratedAt.Format("2006-01-02 15:04:05 UTC")

	return strings.Join([]string{
		"# Tavok Configuration",
		fmt.Sprintf("# Generated by tavok init on %s", generatedAt),
		"# Keep this file secret. Never commit it to git.",
		"",
		"DOMAIN=" + config.Domain,
		"NEXTAUTH_URL=" + config.NextAuthURL,
		"NEXT_PUBLIC_GATEWAY_URL=" + config.GatewayURL,
		"",
		"POSTGRES_USER=tavok",
		"POSTGRES_PASSWORD=" + config.PostgresPassword,
		"POSTGRES_DB=tavok",
		fmt.Sprintf("DATABASE_URL=postgresql://tavok:%s@db:5432/tavok", config.PostgresPassword),
		"",
		"NEXTAUTH_SECRET=" + config.NextAuthSecret,
		"JWT_SECRET=" + config.JWTSecret,
		"INTERNAL_API_SECRET=" + config.InternalAPISecret,
		"SECRET_KEY_BASE=" + config.SecretKeyBase,
		"ENCRYPTION_KEY=" + config.EncryptionKey,
		"",
		"GATEWAY_PORT=4001",
		"STREAMING_PORT=4002",
		"",
		"NODE_ENV=production",
		"MIX_ENV=prod",
		"",
	}, "\n")
}

func WriteEnvFile(path string, config Config, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists", path)
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	if err := os.WriteFile(path, []byte(RenderEnv(config)), 0o600); err != nil {
		return fmt.Errorf("write env file: %w", err)
	}

	return nil
}

func NewSecrets() (Secrets, error) {
	nextAuthSecret, err := randomBase64(32)
	if err != nil {
		return Secrets{}, err
	}

	jwtSecret, err := randomBase64(32)
	if err != nil {
		return Secrets{}, err
	}

	internalAPISecret, err := randomBase64(32)
	if err != nil {
		return Secrets{}, err
	}

	secretKeyBase, err := randomBase64(64)
	if err != nil {
		return Secrets{}, err
	}

	encryptionKey, err := randomHex(32)
	if err != nil {
		return Secrets{}, err
	}

	postgresPassword, err := randomAlphaNumeric(20)
	if err != nil {
		return Secrets{}, err
	}

	return Secrets{
		NextAuthSecret:    nextAuthSecret,
		JWTSecret:         jwtSecret,
		InternalAPISecret: internalAPISecret,
		SecretKeyBase:     secretKeyBase,
		EncryptionKey:     encryptionKey,
		PostgresPassword:  postgresPassword,
	}, nil
}

func normalizeDomain(domain string) string {
	trimmed := strings.TrimSpace(domain)
	if trimmed == "" {
		return "localhost"
	}

	trimmed = strings.TrimPrefix(trimmed, "https://")
	trimmed = strings.TrimPrefix(trimmed, "http://")

	return strings.TrimRight(trimmed, "/")
}

func randomBase64(size int) (string, error) {
	bytes, err := randomBytes(size)
	if err != nil {
		return "", err
	}

	return base64.StdEncoding.EncodeToString(bytes), nil
}

func randomHex(size int) (string, error) {
	bytes, err := randomBytes(size)
	if err != nil {
		return "", err
	}

	return hex.EncodeToString(bytes), nil
}

func randomAlphaNumeric(length int) (string, error) {
	const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

	bytes, err := randomBytes(length)
	if err != nil {
		return "", err
	}

	result := make([]byte, length)
	for i := range bytes {
		result[i] = alphabet[int(bytes[i])%len(alphabet)]
	}

	return string(result), nil
}

func randomBytes(size int) ([]byte, error) {
	bytes := make([]byte, size)
	if _, err := rand.Read(bytes); err != nil {
		return nil, fmt.Errorf("generate random bytes: %w", err)
	}

	return bytes, nil
}
