package bootstrap

import (
	"bytes"
	"crypto/rand"
	_ "embed"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

//go:embed docker-compose.yml
var DockerComposeYML []byte

type Secrets struct {
	NextAuthSecret    string
	JWTSecret         string
	InternalAPISecret string
	SecretKeyBase     string
	EncryptionKey     string
	PostgresPassword  string
	RedisPassword     string
	AdminToken        string
}

type Config struct {
	Domain            string
	GeneratedAt       time.Time
	NextAuthURL       string
	GatewayURL        string
	BindAddress       string
	PostgresPassword  string
	RedisPassword     string
	NextAuthSecret    string
	JWTSecret         string
	InternalAPISecret string
	SecretKeyBase     string
	EncryptionKey     string
	AdminToken        string
}

// TavokConfig is written to .tavok.json for SDK auto-discovery.
// Contains ONLY topology info — no secrets.
type TavokConfig struct {
	URL        string `json:"url"`
	GatewayURL string `json:"gatewayUrl"`
	ServerID   string `json:"serverId"`
	ChannelID  string `json:"channelId"`
}

// BootstrapRequest is the POST body for /api/v1/bootstrap.
type BootstrapRequest struct {
	Email       string `json:"email"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
	ServerName  string `json:"serverName"`
}

// BootstrapResponse is the parsed response from /api/v1/bootstrap.
type BootstrapResponse struct {
	Admin struct {
		Email    string `json:"email"`
		Username string `json:"username"`
	} `json:"admin"`
	Server struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"server"`
	Channel struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"channel"`
	URLs struct {
		Web     string `json:"web"`
		Gateway string `json:"gateway"`
	} `json:"urls"`
}

func BuildConfig(domain string, generatedAt time.Time, secrets Secrets) Config {
	normalizedDomain := normalizeDomain(domain)
	nextAuthURL := "http://localhost:5555"
	gatewayURL := "ws://localhost:4001/socket"
	bindAddress := "127.0.0.1" // Safe default: localhost only

	if normalizedDomain != "localhost" {
		nextAuthURL = fmt.Sprintf("https://%s", normalizedDomain)
		gatewayURL = fmt.Sprintf("wss://%s/socket", normalizedDomain)
		bindAddress = "0.0.0.0" // Production: Caddy handles ingress
	}

	return Config{
		Domain:            normalizedDomain,
		GeneratedAt:       generatedAt.UTC(),
		NextAuthURL:       nextAuthURL,
		GatewayURL:        gatewayURL,
		BindAddress:       bindAddress,
		PostgresPassword:  secrets.PostgresPassword,
		RedisPassword:     secrets.RedisPassword,
		NextAuthSecret:    secrets.NextAuthSecret,
		JWTSecret:         secrets.JWTSecret,
		InternalAPISecret: secrets.InternalAPISecret,
		SecretKeyBase:     secrets.SecretKeyBase,
		EncryptionKey:     secrets.EncryptionKey,
		AdminToken:        secrets.AdminToken,
	}
}

func RenderEnv(config Config) string {
	generatedAt := config.GeneratedAt.Format("2006-01-02 15:04:05 UTC")

	return strings.Join([]string{
		"# Tavok Configuration",
		fmt.Sprintf("# Generated by tavok init on %s", generatedAt),
		"# Keep this file secret. Never commit it to git.",
		"",
		"DOMAIN=" + config.Domain,
		"NEXTAUTH_URL=" + config.NextAuthURL,
		"NEXT_PUBLIC_GATEWAY_URL=" + config.GatewayURL,
		"",
		"# Network binding: 127.0.0.1 = localhost only (safe default),",
		"# 0.0.0.0 = all interfaces (production with Caddy/TLS)",
		"BIND_ADDRESS=" + config.BindAddress,
		"",
		"POSTGRES_USER=tavok",
		"POSTGRES_PASSWORD=" + config.PostgresPassword,
		"POSTGRES_DB=tavok",
		fmt.Sprintf("DATABASE_URL=postgresql://tavok:%s@db:5432/tavok", config.PostgresPassword),
		"",
		"REDIS_PASSWORD=" + config.RedisPassword,
		"",
		"NEXTAUTH_SECRET=" + config.NextAuthSecret,
		"JWT_SECRET=" + config.JWTSecret,
		"INTERNAL_API_SECRET=" + config.InternalAPISecret,
		"SECRET_KEY_BASE=" + config.SecretKeyBase,
		"ENCRYPTION_KEY=" + config.EncryptionKey,
		"",
		"# Admin token for CLI bootstrap (scoped to /api/v1/bootstrap only)",
		"TAVOK_ADMIN_TOKEN=" + config.AdminToken,
		"",
		"GATEWAY_PORT=4001",
		"STREAMING_PORT=4002",
		"",
		"NODE_ENV=production",
		"MIX_ENV=prod",
		"",
	}, "\n")
}

func WriteEnvFile(path string, config Config, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists", path)
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	if err := os.WriteFile(path, []byte(RenderEnv(config)), 0o600); err != nil {
		return fmt.Errorf("write env file: %w", err)
	}

	return nil
}

func NewSecrets() (Secrets, error) {
	nextAuthSecret, err := randomBase64(32)
	if err != nil {
		return Secrets{}, err
	}

	jwtSecret, err := randomBase64(32)
	if err != nil {
		return Secrets{}, err
	}

	internalAPISecret, err := randomBase64(32)
	if err != nil {
		return Secrets{}, err
	}

	secretKeyBase, err := randomBase64(64)
	if err != nil {
		return Secrets{}, err
	}

	encryptionKey, err := randomHex(32)
	if err != nil {
		return Secrets{}, err
	}

	postgresPassword, err := randomAlphaNumeric(20)
	if err != nil {
		return Secrets{}, err
	}

	// Redis password MUST be URL-safe because the Go streaming service
	// parses it as part of a redis:// URL. Base64 contains /, +, = which
	// break URL parsing. Use alphanumeric instead (DEC-0057).
	redisPassword, err := randomAlphaNumeric(32)
	if err != nil {
		return Secrets{}, err
	}

	adminToken, err := randomHex(32)
	if err != nil {
		return Secrets{}, err
	}

	return Secrets{
		NextAuthSecret:    nextAuthSecret,
		JWTSecret:         jwtSecret,
		InternalAPISecret: internalAPISecret,
		SecretKeyBase:     secretKeyBase,
		EncryptionKey:     encryptionKey,
		PostgresPassword:  postgresPassword,
		RedisPassword:     redisPassword,
		AdminToken:        adminToken,
	}, nil
}

// WriteDockerCompose writes the embedded docker-compose.yml to the given directory.
func WriteDockerCompose(dir string, force bool) error {
	path := filepath.Join(dir, "docker-compose.yml")

	if !force {
		if _, err := os.Stat(path); err == nil {
			return nil // Already exists, skip
		}
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	return os.WriteFile(path, DockerComposeYML, 0o644)
}

// WriteTavokConfig writes .tavok.json with connection topology (no secrets).
func WriteTavokConfig(dir string, cfg TavokConfig) error {
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(dir, ".tavok.json"), data, 0o644)
}

// WriteCredentials writes admin credentials to .tavok-credentials (mode 0600).
func WriteCredentials(dir, email, password string) error {
	content := fmt.Sprintf(
		"# Tavok Admin Credentials — for HUMAN web UI login only\n# Agents use API keys from POST /api/v1/agents/register\n# DELETE THIS FILE after your first login\nemail=%s\npassword=%s\n",
		email, password,
	)
	return os.WriteFile(filepath.Join(dir, ".tavok-credentials"), []byte(content), 0o600)
}

// WriteGitignore creates or appends to .gitignore to exclude Tavok secrets.
// If .gitignore already exists, it appends only missing entries.
func WriteGitignore(dir string) error {
	path := filepath.Join(dir, ".gitignore")
	entries := []string{".env", ".tavok-credentials", ".tavok.json"}

	existing := ""
	if data, err := os.ReadFile(path); err == nil {
		existing = string(data)
	}

	var toAdd []string
	for _, entry := range entries {
		// Check if entry already present as a whole line
		found := false
		for _, line := range strings.Split(existing, "\n") {
			if strings.TrimSpace(line) == entry {
				found = true
				break
			}
		}
		if !found {
			toAdd = append(toAdd, entry)
		}
	}

	if len(toAdd) == 0 {
		return nil // All entries already present
	}

	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("open .gitignore: %w", err)
	}
	defer f.Close()

	// Add a newline separator if file exists and doesn't end with one
	if existing != "" && !strings.HasSuffix(existing, "\n") {
		if _, err := f.WriteString("\n"); err != nil {
			return err
		}
	}

	// Add header comment if this is a new file or no Tavok entries existed
	if existing == "" {
		if _, err := f.WriteString("# Tavok — secrets and local config\n"); err != nil {
			return err
		}
	}

	for _, entry := range toAdd {
		if _, err := f.WriteString(entry + "\n"); err != nil {
			return err
		}
	}

	return nil
}

// PollHealth polls the health endpoint until it responds 200 or timeout.
func PollHealth(baseURL string, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	client := &http.Client{Timeout: 5 * time.Second}

	for time.Now().Before(deadline) {
		resp, err := client.Get(baseURL + "/api/health")
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode == 200 {
				return nil
			}
		}
		time.Sleep(2 * time.Second)
	}

	return fmt.Errorf("health check timed out after %s", timeout)
}

// CallBootstrap calls POST /api/v1/bootstrap with the admin token.
func CallBootstrap(baseURL, adminToken string, req BootstrapRequest) (*BootstrapResponse, error) {
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	httpReq, err := http.NewRequest("POST", baseURL+"/api/v1/bootstrap", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Authorization", "Bearer admin-"+adminToken)

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("bootstrap request: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode == 403 {
		// Already bootstrapped — not an error for idempotent init
		return nil, nil
	}

	if resp.StatusCode != 201 {
		return nil, fmt.Errorf("bootstrap failed (HTTP %d): %s", resp.StatusCode, string(respBody))
	}

	var result BootstrapResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("parse response: %w", err)
	}

	return &result, nil
}

// CheckPort returns nil if the TCP port is available, or an error if it's in use.
func CheckPort(port int) error {
	ln, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
	if err != nil {
		return fmt.Errorf("port %d is already in use", port)
	}
	ln.Close()
	return nil
}

// GeneratePassword creates a random 16-character alphanumeric password.
func GeneratePassword() (string, error) {
	return randomAlphaNumeric(16)
}

// ParseEnvSecrets reads an existing .env file and extracts the secrets.
// Used for idempotent re-runs: reuse existing secrets instead of regenerating
// (which would break DB volumes that were initialized with the old password).
func ParseEnvSecrets(path string) (Secrets, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Secrets{}, fmt.Errorf("read env file: %w", err)
	}

	vars := make(map[string]string)
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if idx := strings.Index(line, "="); idx > 0 {
			key := line[:idx]
			value := line[idx+1:]
			vars[key] = value
		}
	}

	s := Secrets{
		NextAuthSecret:    vars["NEXTAUTH_SECRET"],
		JWTSecret:         vars["JWT_SECRET"],
		InternalAPISecret: vars["INTERNAL_API_SECRET"],
		SecretKeyBase:     vars["SECRET_KEY_BASE"],
		EncryptionKey:     vars["ENCRYPTION_KEY"],
		PostgresPassword:  vars["POSTGRES_PASSWORD"],
		RedisPassword:     vars["REDIS_PASSWORD"],
		AdminToken:        vars["TAVOK_ADMIN_TOKEN"],
	}

	// Validate that at least the critical secrets exist
	if s.AdminToken == "" {
		return Secrets{}, fmt.Errorf("TAVOK_ADMIN_TOKEN not found in %s", path)
	}

	return s, nil
}

func normalizeDomain(domain string) string {
	trimmed := strings.TrimSpace(domain)
	if trimmed == "" {
		return "localhost"
	}

	trimmed = strings.TrimPrefix(trimmed, "https://")
	trimmed = strings.TrimPrefix(trimmed, "http://")

	return strings.TrimRight(trimmed, "/")
}

func randomBase64(size int) (string, error) {
	bytes, err := randomBytes(size)
	if err != nil {
		return "", err
	}

	return base64.StdEncoding.EncodeToString(bytes), nil
}

func randomHex(size int) (string, error) {
	bytes, err := randomBytes(size)
	if err != nil {
		return "", err
	}

	return hex.EncodeToString(bytes), nil
}

func randomAlphaNumeric(length int) (string, error) {
	const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

	bytes, err := randomBytes(length)
	if err != nil {
		return "", err
	}

	result := make([]byte, length)
	for i := range bytes {
		result[i] = alphabet[int(bytes[i])%len(alphabet)]
	}

	return string(result), nil
}

func randomBytes(size int) ([]byte, error) {
	bytes := make([]byte, size)
	if _, err := rand.Read(bytes); err != nil {
		return nil, fmt.Errorf("generate random bytes: %w", err)
	}

	return bytes, nil
}
